### ISSUE TITLE
Version must be a string in the boxfile.yml

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox-engine-nodejs#13]
If the node version is specified as an integer in the boxfile.yml, the build will fail.

```yaml
code.build:
  engine: nodejs#refactor/v1
  config:
    version: 4.4
```

But if specified as a string (`'4.4'`), it works. Is it possible to make both work?
