### ISSUE TITLE
Allow users to specify python version

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox-engine-nodejs#23]
There are some npm package that require python2. The engine includes the 'python' package which pulls python-3. If a user tries to add the `python-2` package as an `extra_package`, the packages conflict and the most recent version is used.

We should probably allow users to specify the python version in the engine config. It would default to the most recent, and only change when specified.

```yaml
run.config:
  engine: nodejs
  engine.config:
    python_version: "2.7"
```
